### ISSUE TITLE
'g2 lg' doesn't work 

### ISSUE THREAD

**Issue by seagle0128** [fisherman/g2#1]
Hi, Thanks for the great tool "g2'!

When I running `g lg` with fish 2.4.0 on Cygwin and on Ubuntu 16.04, I got this error:
```
more: unknown -r
```
While it works well on macOSX 12.12.

I checked the function __g2_lg. Unfortunately GNU 'more' has not '-r' parameter. On macOS, more equals to less actually. so I have to `alias more=less` to address this issue on Cygwin and Linux.

```fish
function __g2_lg
    if test (count $argv) -eq 0
        command git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative | more -r
    else
        command git log $argv
    end
end
```

**Comment by jbucaran** [comment]
g2 could check the OS and choose the appropriate flags. What do you think @orefalo?

**Comment by orefalo** [comment]
I think that checking for OS specifics is a great idea to accommodate the different command flavors.

I recently turned off the default git PAGER, therefore had to enable pagination at a command level using **more**. The -r flag on osx enables raw control sequences for coloring. What would be an equivalent command on Cygwin ? or maybe a better solution?

PS: Glad to see people using g2

**Comment by seagle0128** [comment]
@orefalo I think `more` or `less -r` is fine. I went through `glol` in oh-my-zsh and no pipes there.

```shell
➜  ~ alias glol
glol='git log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'
```

**Comment by jbucaran** [comment]
@seagle0128 I thought:

```
more: unknown -r
```

was the problem you were having though.

**Comment by seagle0128** [comment]
@jbucaran yes. The problem is `more` has no `-r` parameter.

**Comment by jbucaran** [comment]
@seagle0128 Gotcha. I was thrown off a bit because of your comment:

> I think more or less -r is fine.

Which I interpreted as more -r or less -r

Nevermind and sorry @orefalo for the noise.

**Comment by orefalo** [comment]
That's the point, here they use the native git pager, no pipe required

If you check the git configuration settings you will see that the pager has been disabled. I had issues with it with other commands.

**Comment by seagle0128** [comment]
@jbucaran sorry for the confusion! I meant just `more` or `less -r` is good. `more` has no `-r` parameter.

**Comment by orefalo** [comment]
should be fixed,  run `fisher update`
   using more on osx as less forces a keypress even when the log is smaller than a page, hate it.

**Comment by seagle0128** [comment]
Great! it works well.
Close it.
