### ISSUE TITLE
completion not works sometimes

### ISSUE THREAD

**Issue by robertluo** [fisherman/g2#3]
Often times when I input "g <TAB>", it just show up  the file list, not the commands, however, sometimes it works, I still can not figure out when.

After a fresh install, it always works though.

**Comment by bkono** [comment]
Realize this is an old issue, but just curious if anyone has come up with a fix for it yet. Impressed by the tool's approach vs porting dozens of my old aliases over from zsh, but the constant loss of autocomplete is driving me batty. @robertluo did you have any luck resolving this?

**Comment by CumpsD** [comment]
rename `g2.fish` in completions to `g.fish`

From https://fishshell.com/docs/current/index.html#completion
>  A completion file must have a filename consisting of the name of the command to complete and the suffix '.fish'.

**Comment by CumpsD** [comment]
If you merge https://github.com/fisherman/g2/pull/5 it should be fixed :)

**Comment by robertluo** [comment]
It works! thanks @CumpsD
