### ISSUE TITLE
This thing looks sick!

### ISSUE THREAD

**Issue by BarbzYHOOL** [fisherman/g2#6]
I'm used to my abbreviations so I'm a bit hesitant to try g2 but it looks really interesting.

It doesn't add abbreviations right?

**Comment by orefalo** [comment]
Hi, save your .gitconfig before testing.

I don't understand your question.

**Comment by BarbzYHOOL** [comment]
It does not add new abbreviations ?

**Comment by orefalo** [comment]
If abbreviations are aliases, it does

If abbreviations are not aliases, no idea..

I think the best it just to read the core, it's trivial

**Comment by BarbzYHOOL** [comment]
ok it does not, but well abbreviations may be new for you in fish if you don't use it anymore
